# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(BuildID)

trigger:
  - main
  - feature/*

variables:
  isMaster: $[eq(variables['build.sourceBranch'], 'refs/heads/master')]
pool:
    vmImage: 'ubuntu-latest'  
  
steps:
  - task: UseNode@1
    inputs:
      version: '16.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm run test
    displayName: 'npm test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
         src/*
         public/*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy project files'
    
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables.isMaster, true))
    inputs:
      artifactName: ncea-frontend_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'

  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables.isMaster, true))
    inputs:
      artifactName: ncea-frontend_
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'