# Starter pipeline
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - main
  - features/*
  - feature/*

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  branchSource: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  branch: $[replace(variables['branchSource'], '/', '-')]

pool:
    vmImage: 'ubuntu-latest'  
  
steps:
  - task: UseNode@1
    inputs:
      version: '16.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm run test
    displayName: 'npm test'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
         build/*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy project files'

  - script: |
      echo "Branch name: $(branch)"
      echo "Artifact name1: ncea-frontend_$(Year:YYYY).$(Month).$(DayOfMonth)"
      echo "Artifact name2: ncea-frontend_$(Date:yyyyMMdd)"

  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables.isMaster, true))
    inputs:
      artifactName: 'ncea-frontend_$(branch)_$(Build.BuildNumber)'
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'

  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables.isMaster, true))
    inputs:
      artifactName: 'ncea-frontend_$(Build.BuildNumber)'
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'