# Starter pipeline
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - features/*
      - feature/*

variables:

  ACR.Name: nceapocsbox
  ACR.ResourceGroupName: NCEA-NW-POC
  ACR.ServiceConnection : acr-AZR-NCE-SND1
  AKS.ServiceConnection : aksServiceConn-AZR-NCE-SND1
  ACR.ContainerRepository: defra/ncea-fe

stages:
- stage: 'Build'
  displayName: 'Build FE'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
      demands:
      - npm

    variables:
      isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
      isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
      branchSource: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
      branch: $[replace(variables['branchSource'], '/', '-')]
      ${{ if ne(variables.isMain, 'true') }}:
        artifactNameSuffix: _$(branch)
      ${{ else }}:
        artifactNameSuffix: ''
      chartPath: 'ncea-fe'
      
    steps:
      - template: steps-build-and-test.yaml
      - template: steps-build-and-push-docker-images.yaml
      - template: steps-package-and-push-helm-charts.yaml

# - stage: 'sandbox'
#   displayName: 'Deploy to the sandbox environment'
#   dependsOn: Build
#   condition:  succeeded()
#   jobs:
#   - deployment: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     environment: sandbox 
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#             - template: steps-deploy-helm-charts.yaml

# - stage: 'dev'
#   displayName: 'Deploy to the dev environment'
#   dependsOn: Build
#   condition:  succeeded()
#   jobs:
#   - deployment: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     environment: dev 
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#             - template: steps-deploy-helm-charts.yaml

# - stage: 'test'
#   displayName: 'Deploy to the test environment'
#   dependsOn: dev
#   condition:  succeeded()
#   jobs:
#   - deployment: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     environment: test 
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#             - template: steps-deploy-helm-charts.yaml