replicaCount: 1

image:
  repository: devnceinfcr1401.azurecr.io/defra/ncea-fe
  pullPolicy: IfNotPresent
  tag: 20240225.19_feature-308801-create-deployment-pipeline

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:  
  create: false 
  automount: false  
  annotations: {}  
  name: "saccount-ncea-devnceinfid1401"

podAnnotations: {}
podLabels: 
  azure.workload.identity/use: "true"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: dev-ncea-search.azure.defra.cloud
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  PORT: 80
  NODE_ENV: sandbox  
  AZURE_KEYVAULT_URL: https://devnceinfkvt1401.vault.azure.net/
  ELASTICSEARCH_API: http://elasticsearch.geonetwork.svc.cluster.local/
  CLASSIFIER_API: https://dev-ncea-classifier.azure.defra.cloud/
  CLASSIFIER_API_AUTHORITY: https://login.microsoftonline.com/b0a4086e-0a02-47f6-b6b0-0197b4eeeff9
  WEBDOMAIN: https://dev-ncea-search.azure.defra.cloud/
  GTM_ID: GTM-PZJ4WBG7
