replicaCount: 1

image:
  repository: 
  pullPolicy: IfNotPresent
  tag: 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:  
  create: false 
  automount: false  
  annotations: {}  
  name: 

podAnnotations: {}
podLabels: 
  azure.workload.identity/use: "true"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "webapprouting.kubernetes.azure.com"
  annotations: {}
  hosts:
    - host: 
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  HOST:
  PORT:
  NODE_ENV:
  APPINSIGHTS_SECRET_NAME: ApplicationInsights--ConnectionString
  AZURE_KEYVAULT_URL:
  ELASTICSEARCH_API: