- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: ELASTICSEARCH_API
  value: "http://elasticsearch.geonetwork.svc.cluster.local:9200/"
- key: NODE_ENV
  value: "dev"
- key: PORT
  value: "80"
